title: Roopesh Shetty
description: Simulation & Reliability Engineer | CAE Automation Specialist
theme: jekyll-theme-cayman

url: "https://roopeshshetty16.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
