title: Roopesh Shetty
description: Simulation & Reliability Engineer | CAE Automation Specialist
theme: jekyll-theme-cayman

url: "https://roopeshshetty16.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag

author:
  name: Roopesh Shetty
  email: roopeshshetty169@gmail.com

github_username: RoopeshShetty16
linkedin_username: Roopesh Shetty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
